Rework project repository clone
ansible/eda-server pull request #216
Opened 2022-10-14 18:22 UTC by cutwater

* Fix `git clone` waiting for interactive input when trying to clone private or non-existing GitHub repository.
* Add timeout for `git` commands.
* The `git_hash` project field is now read only.

Resolves: https://issues.redhat.com/browse/AAP-4833
Resolves: https://issues.redhat.com/browse/AAP-6185

2022-10-14 18:23 UTC, cutwater commented
**Note:** Further refactoring is needed and will be done in subsequent PRs.

2022-10-17 10:23 UTC, Alex-Izquierdo requested changes

2022-10-17 10:23 UTC, Alex-Izquierdo commented on src/eda_server/utils/subprocess.py
> +    timeout: int = None,
This should be Optional if the default is None, isn't?

2022-10-17 10:23 UTC, Alex-Izquierdo commented on src/eda_server/utils/subprocess.py
> +    timeout: int = None,
Should we have a sane default value for timeout?

2022-10-17 10:57 UTC, Alex-Izquierdo approved these changes
Verified

2022-10-17 12:07 UTC, Alex-Izquierdo approved these changes

2022-10-19 12:33 UTC, ddonahue007 approved these changes
lgtm

2022-10-19 16:03 UTC, Alex-Izquierdo approved these changes

2022-10-19 16:06 UTC, merged