AAP 6064 ruleset rules sources + 🌟 Bonus 🌟
ansible/eda-server pull request #249
Opened 2022-11-09 03:44 UTC by Red-HAP

## Index

* [Jira Ticket](#jira-ticket)
* [Description](#description)
    * [Ticket Changes](#ticket-changes)
        * [Ruleset Sources](#ruleset-sources)
        * [Rule Firing Statistics](#rule-firing-statistics)
    * [Workflow Changes](#workflow-changes)
        * [Base SQL](#base-sql)
        * [Module SQL](#module-sql)
* [Data Shapes](#data-shapes)
* [Testing](#testing)

## Jira Ticket

[AAP-6064](https://issues.redhat.com/browse/AAP-6064)

## Description

This PR will apply the changes described in the ticket as well as introducing a new development workflow where the query builders are moved to a separate module and imported by the API handlers.

### Ticket Changes

#### Ruleset Sources

Adds a sources `JSONB` column to the `ruleset` table.

Performs a parse of the source information from the rulebook ruleset data definition. The result of this parse will be an array of the following dict:

```python
{
    "name": text,  # from yaml
    "source": text,  # from yaml
    "type": text,  # parsed as source.split(".")[-1]
    "config": dict,  # from yaml
}
```

This parsing operation is performed as part of the `insert_rulebook_related_data()` call.

These sources are now part of the ruleset list and ruleset detail return structures. In the list result, the source types are returned. In the detail result, the full sources column data is returned.

#### Rule Firing Statistics

Rule fire count statistics are captured from the `audit_rule` table. These statistics are a rule status count over total status count over a window of (now - 30 days) to now. This also calculates a percentage of the object-status count over the status total or the status total by date (detail only). This will provide context to the count numbers and could be rendered as a chart in the UI.

These firing statistics are returned on ruleset list and detail as well as rule list and detail.

### Workflow Changes

The workflow change here should be that SQL query builders via SQLAlchemy or other means are moved to a new module corresponding to wither a base (common) module or to a module that is specific to a common set of endpoints. 

This work has begun as of this PR. The base sql module is `src/eda_server/db/sql/base/__init__.py`. There is a new module to build and execute the queries for rule, ruleset, and rulebook queries have been moved from the api handlers to functions in `src/eda_server/db/sql/rulebook/__init__.py`.

Tests have been added to `tests/db/sql/`. The pytest setup code has been relocated from `tests/integration/...` to `tests/`. The design philosophy is to only need the `db` fixture for the `tests/db/...` tests and full integration fixtures for `tests/integration/...`.

#### Base SQL

The base functions will build simple select statements and simple insert statements and a handful of executors. Executors that return a specific query record result will return that result as a `sqlalchemy.engine.Row` object. A collection of results will be returned as a `sqlalchemy.engine.CursorResult` object.

#### Module SQL

The functions in the module SQL are intended to build the queries to provide the data for the endpoints. Executor functions were also created for the minimal number of imports needed in the API handler file.

## Data Shapes

### List Rules

```python
# endpoint: api/rules
[
  {
    "id": 0,
    "name": "string",
    "ruleset": {
      "id": 0,
      "name": "string"
    },
    "rulebook": {
      "id": 0,
      "name": "string"
    },
    "project": {
      "id": 0,
      "name": "string"
    },
    "fired_stats": [
      {
        "total_type": "string",
        "status": "string",
        "status_total": 0,
        "object_total": 0,
        "pct_object_total": 0,
        "window_total": 0,
        "pct_window_total": 0
      },
      ...
    ]
  },
  ...
]
```

### Get Rule

```python
# endpoint: api/rules/{rule_id}
{
  "id": 0,
  "name": "string",
  "action": {},
  "ruleset": {
    "id": 0,
    "name": "string"
  },
  "rulebook": {
    "id": 0,
    "name": "string"
  },
  "project": {
    "id": 0,
    "name": "string"
  },
  "fired_stats": [
    {
      "total_type": "string",
      "fired_date": "2022-11-09",
      "object_status": "string",
      "object_status_total": 0,
      "pct_date_status_total": 0,
      "window_total": 0,
      "pct_window_total": 0
    },
    ...
  ]
}
```

### List Rulesets

```python
# endpoint: api/rulesets
[
  {
    "id": 0,
    "name": "string",
    "rule_count": 0,
    "source_types": ["string", ...],
    "created_at": "2022-11-09T03:12:39.532Z",
    "modified_at": "2022-11-09T03:12:39.532Z",
    "fired_stats": [
      {
        "total_type": "string",
        "status": "string",
        "status_total": 0,
        "object_total": 0,
        "pct_object_total": 0,
        "window_total": 0,
        "pct_window_total": 0
      },
      ...
    ]
  },
  ...
]
```

### Get Ruleset

```python
# endpoint: api/rulesets/{ruleset_id}
{
  "id": 0,
  "name": "string",
  "rule_count": 0,
  "created_at": "2022-11-09T03:15:16.757Z",
  "modified_at": "2022-11-09T03:15:16.757Z",
  "sources": [
    {
      "name": "string",
      "type": "string",
      "source": "string",
      "config": {}
    },
    ...
  ],
  "rulebook": {
    "id": 0,
    "name": "string"
  },
  "project": {
    "id": 0,
    "name": "string"
  },
  "fired_stats": [
    {
      "total_type": "string",
      "fired_date": "2022-11-09",
      "object_status": "string",
      "object_status_total": 0,
      "pct_date_status_total": 0,
      "window_total": 0,
      "pct_window_total": 0
    },
    ...
  ]
}
```

### List Ruleset Rules

```python
# endpoint: api/rulesets/{ruleset_id}/rules
[
  {
    "id": 0,
    "name": "string",
    "ruleset": {
      "id": 0,
      "name": "string"
    },
    "rulebook": {
      "id": 0,
      "name": "string"
    },
    "project": {
      "id": 0,
      "name": "string"
    },
    "fired_stats": [
      {
        "total_type": "string",
        "status": "string",
        "status_total": 0,
        "object_total": 0,
        "pct_object_total": 0,
        "window_total": 0,
        "pct_window_total": 0
      },
      ...
    ]
  },
  ...
]
```

### List Rulebooks

```python
# endpoint: api/rulebooks
[
  {
    "id": 0,
    "name": "string",
    "ruleset_count": 0
  },
  ...
]
```

### Get Rulebooks

```python
# endpoint: api/rulebooks
{
  "id": 0,
  "name": "string",
  "description": "",
  "ruleset_count": 0,
  "created_at": "2022-11-09T03:19:53.807Z",
  "modified_at": "2022-11-09T03:19:53.807Z"
}
```

### List Rulebook Rulesets

```python
# endpoint: api/rulebooks
[
  {
    "id": 0,
    "name": "string",
    "rule_count": 0,
    "source_types": [
      "string"
    ],
    "created_at": "2022-11-09T03:20:54.530Z",
    "modified_at": "2022-11-09T03:20:54.530Z",
    "fired_stats": [
      {
        "total_type": "string",
        "status": "string",
        "status_total": 0,
        "object_total": 0,
        "pct_object_total": 0,
        "window_total": 0,
        "pct_window_total": 0
      },
      ...
    ]
  },
  ...
]
```

## Testing

### Migrations

1. Reset database and run migrations
2. Execute `psql postgresql://postgres@localhost:5432/eda_server`
    1. `\d ruleset`
        There should be no `sources` column.
    2. Exit `psql`
3. Execute `task dev:run:migrations`
4. Execute `psql postgresql://postgres@localhost:5432/eda_server`
    1. `\d ruleset`
        There should be a `sources` column with jsonb type.
    2. Exit `psql`

### Create Rulebook

**Sample Ruleset 1**
```yaml
---
- name: Test simple 001
  hosts: all
  sources:
    - name: range
      range:
        limit: 5
  rules:
    - name:
      condition: event.i == 1
      action:
        debug:
```

**Sample Ruleset 2**
```yaml
---
- name: Test simple 001
  hosts: all
  sources:
    - name: range
      range:
        limit: 5
  rules:
    - name:
      condition: event.i == 1
      action:
        debug:

- name: Test simple 002
  hosts: all
  sources:
    - nam [...]

2022-11-09 23:21 UTC, lgalis requested changes
The /api/rulebook/rulesets data differs from the data returned for the matching rulesets in /api/rulesets - the source_types and fired_stats are null:

/api/rulebooks/20/rulesets:
[
  {
    "id": 20,
    "name": "CI/CD Rules",
    "rule_count": 4,
    "source_types": null,
    "created_at": "2022-11-09T22:04:47.048987+00:00",
    "modified_at": "2022-11-09T22:04:47.048987+00:00",
    "fired_stats": null
  }
]

2022-11-10 20:42 UTC, ddonahue007 submitted a review, later dismissed
lgtm

2022-11-11 22:45 UTC, lgalis approved these changes
LGTM

2022-11-11 22:51 UTC, ddonahue007 approved these changes

2022-11-11 22:54 UTC, merged