Add Sync Project Endpoint
ansible/eda-server pull request #286
Opened 2022-12-02 17:42 UTC by Dostonbek1

Adds an API endpoint to sync an existing project.

- refactor importing project files code
- add sync project endpoint `api/projects/<project_id>`

Resolves: AAP-5704

2022-12-08 13:15 UTC, cutwater requested changes

2022-12-08 13:15 UTC, cutwater commented on src/eda_server/project.py
> +        await import_playbook(db, filename, file_content, project_id)
Looks like a candidate for the "dispatch dict" pattern.

2022-12-08 13:15 UTC, cutwater commented on src/eda_server/project.py
> +async def import_rulebook(
Candidates for moving into `db/sql` package

2022-12-08 13:15 UTC, cutwater commented on src/eda_server/project.py
> +    full_path = os.path.join(directory, filename)
The fact that you pass a tuple into a function to only join it indicates that tuple is not needed to be passed to a function at all.

2022-12-08 13:15 UTC, cutwater commented on src/eda_server/project.py
> +async def import_project_file(db: AsyncSession, file, file_type, project_id):
Please add some type annotations. It's completely unclear what the `file` is and it's even more unexpected that this is a tuple of `(directory, filename)`.

2022-12-12 15:05 UTC, ddonahue007 approved these changes
lgtm

2022-12-12 15:05 UTC, abaiken approved these changes

2022-12-12 15:07 UTC, merged