refactor[fanout] decouple source from activation
ansible/eda-server pull request #590
Opened 2024-01-04 20:17 UTC by Alex-Izquierdo

Since the source is a new flavor of activation (understanding an activation as a background rulebook process) implement a new BaseActivation abstract model with common logic and two separated models for rulebook activations and source activations. 

All the names are preserved to keep backward compatibility, only the OneToMany relationship with the activation in the source model is removed.

2024-01-05 17:57 UTC, jshimkus-rh commented on src/aap_eda/core/models/base.py
The file name is too generic and is easily confused as containing a root class for the entire eda server object hierarchy.
It is is activation specific a name reflecting that should be used.

2024-01-08 12:23 UTC, Alex-Izquierdo commented on src/aap_eda/core/models/base.py
I would agree. Is it fine `base-activation`?

2024-01-08 13:20 UTC, Alex-Izquierdo commented on src/aap_eda/core/models/base.py
Anyway I would like to discuss the final implementation because I'm not sure if an Abstract model is what we need instead of multitable inheritance.

2024-01-08 14:12 UTC, jshimkus-rh commented on src/aap_eda/core/models/base.py
> I would agree. Is it fine `base-activation`?

I'm ok with that.

2024-01-08 14:36 UTC, jshimkus-rh commented on src/aap_eda/core/models/base.py
> Anyway I would like to discuss the final implementation because I'm not sure if an Abstract model is what we need instead of multitable inheritance.

I want to be clear on what you're asking particularly regarding multiple inheritance. The following is my perspective...

I prefer a single-inheritance (subclass descends from one superclass) approach (unless otherwise required) except for the situation where the class will be implementing what other languages call an interface or protocol; i.e., if it acts like a duck, it's a duck.  In those situations the abstraction is the interface/protocol and unrelated classes can be used as long as they adhere to the semantic behavior required of the interface.

Such an approach may be overly general for some situations; i.e., if every subclass in a hierarchy does X, Y and Z in the exact same way with, at most, some minor tweaks but fundamentally dependent on common processing.  Making that a general abstraction may be going further than necessary.  Should the need arise to create an abstraction it would be fairly easy to separate the abstraction out and modify the superclass to inherit from the abstraction while leaving the subclasses alone.

2024-01-09 17:15 UTC, benthomasson requested changes

2024-01-09 17:15 UTC, benthomasson commented on src/aap_eda/core/models/base.py
> +    def save(self, *args, **kwargs):
Do not override the save function

2024-01-09 17:19 UTC, benthomasson commented on src/aap_eda/core/models/base.py
> +    def save(self, *args, **kwargs):
Save function is not called on update and doesn't enforce.

2024-01-09 23:05 UTC, closed without merging

2024-01-09 23:05 UTC, Alex-Izquierdo commented
Approach discarded