Change arbirtary default settings yaml path
ansible/eda-server pull request #601
Opened 2024-01-12 19:39 UTC by jamesmarshall24

Update default settings yaml path

2024-01-12 20:00 UTC, Alex-Izquierdo approved these changes

2024-01-16 15:08 UTC, mkanoor approved these changes

2024-01-16 19:10 UTC, Alex-Izquierdo requested changes
on-hold until finish internal discussions about the use of references to AAP.

2024-01-17 02:31 UTC, jamesmarshall24 commented
Taking a different approach

2024-01-17 02:31 UTC, closed without merging