Combine event streams with activations
ansible/eda-server pull request #645
Opened 2024-02-03 03:21 UTC by hsong-rh

2024-02-05 16:27 UTC, benthomasson requested changes
Don't use BigIntegerField for parent_id.  Use separate foreign key fields for activation and event stream.   In fact you have OneToOneField relations on activation and event stream so you already have the backward reference.

2024-02-06 21:18 UTC, mkanoor commented on tests/integration/api/test_event_stream.py
> +#  Copyright 2023 Red Hat, Inc.
@hsong-rh 2024?

2024-02-06 21:19 UTC, mkanoor commented on src/aap_eda/api/views/event_stream.py
> +#  Copyright 2023 Red Hat, Inc.
@hsong-rh 2024?

2024-02-07 17:42 UTC, Alex-Izquierdo commented
Do we want to continue working in this branch?

2024-02-07 18:08 UTC, hsong-rh commented
> Do we want to continue working in this branch?

no, will move all changes to the main branch. Here is a reference.

2024-02-07 18:09 UTC, closed without merging