Add default arg for organization foreign key fields
ansible/eda-server pull request #831
Opened 2024-04-17 17:41 UTC by Dostonbek1

2024-04-17 18:38 UTC, benthomasson commented
@Dostonbek1 where is the default organization created?

2024-04-17 18:39 UTC, benthomasson approved these changes

2024-04-18 01:33 UTC, mkanoor approved these changes

2024-04-18 13:55 UTC, AlanCoding commented on src/aap_eda/services/activation/manager.py
> +            "organization": self.db_instance.organization,
Calling it out in a comment, this is a case where the child inherits the organization from its parent

2024-04-18 13:59 UTC, AlanCoding commented on src/aap_eda/wsapi/consumers.py
> +                organization=activation_org,
second case `AuditRule` (2)

2024-04-18 14:01 UTC, AlanCoding requested changes
Looking for Rulebook to inherit org from project (3)

2024-04-18 15:24 UTC, AlanCoding approved these changes

2024-04-18 15:31 UTC, benthomasson approved these changes

2024-04-18 15:35 UTC, merged